# Generated by Django 3.2.20 on 2023-11-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('abaout', models.CharField(max_length=150)),
                ('offers', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ConfigRifa',
            },
        ),
    ]
